### ISSUE TITLE
Why is the publish directory "out" in the netlify.toml?

### ISSUE THREAD

**Issue by andrewriveradev** [cassidoo/next-netlify-starter#9]
Why is the publish directory "out" in the netlify.toml and not ".next"?

**Comment by flackeryy** [comment]
@andrewriveradev why did you close the thread? Do you know the reason of the **out** directory in this example? As I understand, Next.js outputs the **out** directory only in case of `next export`. But static HTML export doesn't support SSR, which is required for my usecase. So I need to use `next start`, which outputs the **.next** folder.

**Comment by gragland** [comment]
I'm also running into this problem and filed an issue in the plugin repo: https://github.com/netlify/netlify-plugin-nextjs/issues/373
